In [3]:
import torch
from networks import *
from deeppoly import *

In [10]:
SPU()(-0.5)

TypeError: sigmoid(): argument 'input' (position 1) must be Tensor, not float

In [10]:
spu(torch.sqrt(torch.abs(spu(torch.tensor(0)))))


tensor(-2.9802e-08)

In [2]:
a = torch.tensor(
    [
        [1,2,3],
        [1,2,5],
        [1,2,5]
    ]
)

In [7]:
torch.eye(a.size()[0])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
idx_4 = torch.logical_and(
    torch.logical_and(
        torch.logical_not(a == 1),
        torch.logical_not(a == 2)
    ),
    torch.logical_not(a == 3),
)


tensor([[False, False, False],
        [False, False,  True],
        [False, False,  True]])

In [27]:
torch.eye(3, 3).shape[0]

3

In [2]:
import torch

In [9]:
a = torch.tensor(
    [
        [2, 4, 1, 3],
        [1, 2, 3, 2]
    ]
)
b = torch.tensor(
    [
        [2, 4, 1, 3],
        [1, 2, 3, 2]
    ]
)

a * b + b

tensor([[ 6, 20,  2, 12],
        [ 2,  6, 12,  6]])

In [6]:
b = torch.zeros(15, 2)

In [7]:
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [40]:
a = b == 1

In [41]:
2 * b[a]

tensor([])